export const allEmployees = "allEmployees"
export const oneEmployee = "oneEmployee"
export const getError = "getError"
export const createNewEmployee = "createNewEmployee"
export const deleteoneEmployee = "deleteoneEmployee"
export const editoneemployee = "editoneemployee"
export const createNewUser = "createNewUser";
export const loginNewUser = "loginNewUser";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const GET_CURERNT_USER = "GET_CURERNT_USER";
// export const employeesApi = "http://localhost:5555/api/v1/employees"